pipeline {
    agent any

    environment {
        AWS_REGION = 'ap-south-1'
        AWS_ACCOUNT = '098072157119'
        ECR_REPO = "${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/sample-spring-boot-app"
        IMAGE_TAG = 'latest'
        K8S_NAMESPACE = 'dev'
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Maven Build') {
            steps {
                dir('app/sample-spring-boot-app') {
                    sh './mvnw clean compile'
                }
            }
        }

        stage('Run Unit Tests') {
            steps {
                dir('app/sample-spring-boot-app') {
                    sh './mvnw test'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -f docker/Dockerfile -t sample-spring-boot-app:${IMAGE_TAG} ."
            }
        }

        stage('Push to AWS ECR') {
            steps {
		withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', 
                          credentialsId: 'aws-creds', 
                          accessKeyVariable: 'AWS_ACCESS_KEY_ID', 
                          secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {	
                    sh """
                        aws ecr get-login-password --region ${AWS_REGION} | \
                        docker login --username AWS --password-stdin ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com
                        docker tag sample-spring-boot-app:latest 098072157119.dkr.ecr.ap-south-1.amazonaws.com/sample-spring-boot-app:latest
                        docker push ${ECR_REPO}:${IMAGE_TAG}
               		docker system prune -af 
			""" 
                }
            }
        }

        stage('Deploy to Dev Kubernetes') {
            steps {
                sh """
		    kubectl create secret docker-registry ecr-secret \
	              --docker-server=${ECR_REPO} \
        	      --docker-username=AWS \
	              --docker-password=\$(aws ecr get-login-password --region ${AWS_REGION}) \
	              -n ${K8S_NAMESPACE} --dry-run=client -o yaml | kubectl apply -f -
		
                    kubectl apply -f k8s/dev/deployment.yaml
                    kubectl apply -f k8s/dev/service.yaml
		    kubectl rollout restart deployment/sample-spring-boot-app -n ${K8S_NAMESPACE}
                    kubectl rollout status deployment/sample-spring-boot-app -n ${K8S_NAMESPACE} --timeout=120s
                """
            }
        }
    }

    post {
        success {
            echo "✅ Pipeline completed successfully! Image pushed to ECR and deployed to Dev."
        }
        failure {
            echo "❌ Pipeline failed."
        }
    }
}
